finite stochastic language
# number of traces
231
# trace 0
# weight
20385/150370
# number of events
2
Create Fine
Send Fine
# trace 1
# weight
56482/150370
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 2
# weight
9520/150370
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 3
# weight
2497/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 4
# weight
46371/150370
# number of events
2
Create Fine
Payment
# trace 5
# weight
3736/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 6
# weight
443/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 7
# weight
9/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Payment
Add penalty
Send Appeal to Prefecture
# trace 8
# weight
1515/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 9
# weight
61/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 10
# weight
3131/150370
# number of events
3
Create Fine
Send Fine
Payment
# trace 11
# weight
139/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 12
# weight
3301/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 13
# weight
58/150370
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 14
# weight
45/150370
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 15
# weight
89/150370
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 16
# weight
42/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 17
# weight
362/150370
# number of events
3
Create Fine
Payment
Send Fine
# trace 18
# weight
69/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 19
# weight
81/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 20
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 21
# weight
3/150370
# number of events
6
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Payment
# trace 22
# weight
135/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 23
# weight
6/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 24
# weight
108/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 25
# weight
114/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 26
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 27
# weight
6/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Payment
# trace 28
# weight
88/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 29
# weight
12/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 30
# weight
126/150370
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 31
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 32
# weight
12/150370
# number of events
3
Create Fine
Payment
Payment
# trace 33
# weight
2/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 34
# weight
15/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 35
# weight
522/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 36
# weight
49/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 37
# weight
12/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 38
# weight
34/150370
# number of events
4
Create Fine
Send Fine
Payment
Payment
# trace 39
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Payment
Receive Result Appeal from Prefecture
Payment
# trace 40
# weight
7/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
Send Appeal to Prefecture
# trace 41
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Notify Result Appeal to Offender
Receive Result Appeal from Prefecture
Send for Credit Collection
# trace 42
# weight
14/150370
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 43
# weight
4/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Send for Credit Collection
# trace 44
# weight
20/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 45
# weight
10/150370
# number of events
6
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
# trace 46
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 47
# weight
9/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
# trace 48
# weight
32/150370
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
# trace 49
# weight
20/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 50
# weight
20/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 51
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 52
# weight
8/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
Send Appeal to Prefecture
# trace 53
# weight
16/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Send for Credit Collection
# trace 54
# weight
8/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 55
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 56
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 57
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send Appeal to Prefecture
Send for Credit Collection
# trace 58
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 59
# weight
23/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
# trace 60
# weight
9/150370
# number of events
6
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
# trace 61
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 62
# weight
30/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 63
# weight
1/150370
# number of events
16
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 64
# weight
1/150370
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 65
# weight
4/150370
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
# trace 66
# weight
1/150370
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 67
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 68
# weight
11/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection
# trace 69
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 70
# weight
4/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 71
# weight
3/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Send Appeal to Prefecture
# trace 72
# weight
1/150370
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
Payment
# trace 73
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 74
# weight
1/150370
# number of events
17
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 75
# weight
19/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
# trace 76
# weight
1/150370
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 77
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Payment
Payment
Payment
Payment
# trace 78
# weight
19/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 79
# weight
1/150370
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 80
# weight
1/150370
# number of events
16
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 81
# weight
22/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 82
# weight
1/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Receive Result Appeal from Prefecture
# trace 83
# weight
1/150370
# number of events
20
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 84
# weight
5/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Send for Credit Collection
# trace 85
# weight
1/150370
# number of events
4
Create Fine
Appeal to Judge
Send Fine
Payment
# trace 86
# weight
13/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
# trace 87
# weight
4/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 88
# weight
5/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 89
# weight
1/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 90
# weight
1/150370
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Payment
Send Appeal to Prefecture
# trace 91
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
Payment
# trace 92
# weight
3/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
# trace 93
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 94
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 95
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send Appeal to Prefecture
# trace 96
# weight
6/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
# trace 97
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 98
# weight
1/150370
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 99
# weight
56/150370
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 100
# weight
13/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 101
# weight
3/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Send for Credit Collection
# trace 102
# weight
7/150370
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 103
# weight
4/150370
# number of events
7
Create Fine
Send Fine
Payment
Insert Fine Notification
Payment
Add penalty
Payment
# trace 104
# weight
2/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
Send for Credit Collection
# trace 105
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 106
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection
# trace 107
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Notify Result Appeal to Offender
Payment
# trace 108
# weight
14/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
# trace 109
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Add penalty
Payment
# trace 110
# weight
7/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
Payment
# trace 111
# weight
3/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 112
# weight
3/150370
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 113
# weight
3/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 114
# weight
5/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 115
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection
# trace 116
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 117
# weight
4/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 118
# weight
3/150370
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 119
# weight
2/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 120
# weight
12/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 121
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 122
# weight
1/150370
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 123
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
Payment
# trace 124
# weight
9/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 125
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Send for Credit Collection
# trace 126
# weight
20/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Payment
Add penalty
Payment
# trace 127
# weight
15/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 128
# weight
1/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
# trace 129
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 130
# weight
1/150370
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 131
# weight
5/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Send for Credit Collection
# trace 132
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Send for Credit Collection
# trace 133
# weight
3/150370
# number of events
3
Create Fine
Appeal to Judge
Send Fine
# trace 134
# weight
6/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Payment
Add penalty
Send for Credit Collection
# trace 135
# weight
6/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 136
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Send for Credit Collection
# trace 137
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
Notify Result Appeal to Offender
Payment
# trace 138
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Payment
# trace 139
# weight
4/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 140
# weight
7/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
# trace 141
# weight
1/150370
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 142
# weight
6/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
# trace 143
# weight
1/150370
# number of events
7
Create Fine
Payment
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 144
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 145
# weight
5/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 146
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Appeal to Judge
Send Appeal to Prefecture
# trace 147
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
Send Appeal to Prefecture
# trace 148
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 149
# weight
3/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 150
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Send Appeal to Prefecture
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 151
# weight
6/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
# trace 152
# weight
17/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 153
# weight
2/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Payment
# trace 154
# weight
2/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
# trace 155
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 156
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 157
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
Payment
# trace 158
# weight
7/150370
# number of events
3
Create Fine
Send Fine
Appeal to Judge
# trace 159
# weight
1/150370
# number of events
9
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 160
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Add penalty
Send Appeal to Prefecture
# trace 161
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
Payment
# trace 162
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send Appeal to Prefecture
# trace 163
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
# trace 164
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Appeal to Judge
# trace 165
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Appeal to Judge
# trace 166
# weight
2/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 167
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
# trace 168
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Send for Credit Collection
# trace 169
# weight
2/150370
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 170
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
Payment
Payment
# trace 171
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
Payment
Payment
# trace 172
# weight
4/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 173
# weight
1/150370
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 174
# weight
1/150370
# number of events
7
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
# trace 175
# weight
1/150370
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
Payment
# trace 176
# weight
2/150370
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Send Appeal to Prefecture
# trace 177
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Notify Result Appeal to Offender
Receive Result Appeal from Prefecture
# trace 178
# weight
1/150370
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 179
# weight
3/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 180
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
Add penalty
Payment
# trace 181
# weight
1/150370
# number of events
4
Create Fine
Payment
Payment
Send Fine
# trace 182
# weight
1/150370
# number of events
5
Create Fine
Send Fine
Payment
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 183
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Payment
Payment
# trace 184
# weight
1/150370
# number of events
5
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
Payment
# trace 185
# weight
2/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
Payment
# trace 186
# weight
2/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Payment
# trace 187
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 188
# weight
1/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
# trace 189
# weight
3/150370
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Appeal to Judge
# trace 190
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Payment
# trace 191
# weight
3/150370
# number of events
5
Create Fine
Send Fine
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 192
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
# trace 193
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 194
# weight
3/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 195
# weight
3/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 196
# weight
1/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 197
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 198
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Appeal to Judge
Payment
# trace 199
# weight
4/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 200
# weight
1/150370
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Appeal to Judge
# trace 201
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 202
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Insert Fine Notification
Add penalty
Payment
# trace 203
# weight
1/150370
# number of events
7
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 204
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
# trace 205
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 206
# weight
1/150370
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Payment
Payment
Payment
Payment
# trace 207
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
# trace 208
# weight
1/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Send for Credit Collection
# trace 209
# weight
3/150370
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Payment
Payment
Payment
Payment
# trace 210
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 211
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
Send Appeal to Prefecture
# trace 212
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 213
# weight
2/150370
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send Appeal to Prefecture
Send for Credit Collection
# trace 214
# weight
1/150370
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 215
# weight
1/150370
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Send for Credit Collection
# trace 216
# weight
1/150370
# number of events
9
Create Fine
Payment
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 217
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 218
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Payment
# trace 219
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Payment
# trace 220
# weight
1/150370
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 221
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Receive Result Appeal from Prefecture
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 222
# weight
1/150370
# number of events
17
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 223
# weight
1/150370
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 224
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 225
# weight
1/150370
# number of events
7
Create Fine
Send Fine
Send Appeal to Prefecture
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
# trace 226
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Payment
Payment
# trace 227
# weight
1/150370
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Send for Credit Collection
# trace 228
# weight
2/150370
# number of events
7
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
# trace 229
# weight
1/150370
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
Payment
Payment
Payment
Payment
# trace 230
# weight
1/150370
# number of events
8
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Insert Fine Notification
Appeal to Judge
Add penalty
Payment