finite stochastic language
# number of traces
65
# trace 0
# weight
4605/13018
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 1
# weight
2079/13018
# number of events
2
Create Fine
Send Fine
# trace 2
# weight
114/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 3
# weight
4569/13018
# number of events
2
Create Fine
Payment
# trace 4
# weight
253/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 5
# weight
883/13018
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 6
# weight
231/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 7
# weight
47/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 8
# weight
23/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 9
# weight
45/13018
# number of events
3
Create Fine
Send Fine
Payment
# trace 10
# weight
8/13018
# number of events
3
Create Fine
Payment
Send Fine
# trace 11
# weight
4/13018
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 12
# weight
8/13018
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 13
# weight
3/13018
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
# trace 14
# weight
6/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Send for Credit Collection
# trace 15
# weight
17/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 16
# weight
2/13018
# number of events
6
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
# trace 17
# weight
6/13018
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 18
# weight
11/13018
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 19
# weight
16/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 20
# weight
4/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 21
# weight
8/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 22
# weight
8/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 23
# weight
10/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 24
# weight
1/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 25
# weight
1/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 26
# weight
1/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send Appeal to Prefecture
Send for Credit Collection
# trace 27
# weight
4/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 28
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 29
# weight
1/13018
# number of events
20
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 30
# weight
1/13018
# number of events
4
Create Fine
Appeal to Judge
Send Fine
Payment
# trace 31
# weight
4/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
# trace 32
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 33
# weight
2/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 34
# weight
2/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Add penalty
Send Appeal to Prefecture
# trace 35
# weight
3/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
# trace 36
# weight
1/13018
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 37
# weight
1/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 38
# weight
1/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 39
# weight
1/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
Payment
# trace 40
# weight
2/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send Appeal to Prefecture
# trace 41
# weight
1/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
# trace 42
# weight
1/13018
# number of events
3
Create Fine
Appeal to Judge
Send Fine
# trace 43
# weight
1/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Appeal to Judge
# trace 44
# weight
2/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 45
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Appeal to Judge
# trace 46
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 47
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 48
# weight
1/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 49
# weight
1/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
# trace 50
# weight
1/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 51
# weight
1/13018
# number of events
4
Create Fine
Send Fine
Payment
Payment
# trace 52
# weight
2/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 53
# weight
1/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Send for Credit Collection
# trace 54
# weight
1/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Send for Credit Collection
# trace 55
# weight
1/13018
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 56
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 57
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 58
# weight
2/13018
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send Appeal to Prefecture
Send for Credit Collection
# trace 59
# weight
1/13018
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 60
# weight
4/13018
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
# trace 61
# weight
1/13018
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 62
# weight
1/13018
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 63
# weight
1/13018
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 64
# weight
1/13018
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Payment
Payment
Payment
Payment