finite stochastic language
# number of traces
50
# trace 0
# weight
133/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 1
# weight
3029/8001
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 2
# weight
2636/8001
# number of events
2
Create Fine
Payment
# trace 3
# weight
1/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 4
# weight
676/8001
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 5
# weight
20/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 6
# weight
1/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Receive Result Appeal from Prefecture
# trace 7
# weight
83/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 8
# weight
3/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Send for Credit Collection
# trace 9
# weight
7/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 10
# weight
1127/8001
# number of events
2
Create Fine
Send Fine
# trace 11
# weight
11/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 12
# weight
4/8001
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
# trace 13
# weight
167/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 14
# weight
10/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 15
# weight
2/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 16
# weight
8/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 17
# weight
29/8001
# number of events
3
Create Fine
Send Fine
Payment
# trace 18
# weight
3/8001
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 19
# weight
2/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 20
# weight
3/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 21
# weight
2/8001
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 22
# weight
3/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 23
# weight
4/8001
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 24
# weight
1/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Send for Credit Collection
# trace 25
# weight
2/8001
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 26
# weight
1/8001
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 27
# weight
1/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
Payment
Payment
# trace 28
# weight
6/8001
# number of events
3
Create Fine
Payment
Send Fine
# trace 29
# weight
2/8001
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 30
# weight
1/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Payment
# trace 31
# weight
2/8001
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 32
# weight
1/8001
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment
Payment
Payment
# trace 33
# weight
2/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 34
# weight
1/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Payment
Add penalty
Send Appeal to Prefecture
# trace 35
# weight
1/8001
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 36
# weight
1/8001
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 37
# weight
1/8001
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 38
# weight
1/8001
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 39
# weight
1/8001
# number of events
4
Create Fine
Send Fine
Payment
Payment
# trace 40
# weight
2/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
# trace 41
# weight
1/8001
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Send for Credit Collection
# trace 42
# weight
1/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 43
# weight
1/8001
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 44
# weight
1/8001
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 45
# weight
1/8001
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 46
# weight
1/8001
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 47
# weight
1/8001
# number of events
6
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
# trace 48
# weight
2/8001
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 49
# weight
1/8001
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Send for Credit Collection