finite stochastic language
# number of traces
66
# trace 0
# weight
3927/12587
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 1
# weight
1196/12587
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 2
# weight
4007/12587
# number of events
2
Create Fine
Payment
# trace 3
# weight
189/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 4
# weight
26/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 5
# weight
21/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 6
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 7
# weight
311/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 8
# weight
1911/12587
# number of events
2
Create Fine
Send Fine
# trace 9
# weight
587/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 10
# weight
129/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 11
# weight
14/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 12
# weight
1/12587
# number of events
17
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 13
# weight
101/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 14
# weight
3/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Send for Credit Collection
# trace 15
# weight
2/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 16
# weight
4/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
# trace 17
# weight
2/12587
# number of events
3
Create Fine
Payment
Payment
# trace 18
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Send for Credit Collection
# trace 19
# weight
6/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 20
# weight
13/12587
# number of events
3
Create Fine
Send Fine
Payment
# trace 21
# weight
4/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 22
# weight
7/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Payment
Add penalty
Payment
# trace 23
# weight
11/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 24
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 25
# weight
22/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 26
# weight
2/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Send Appeal to Prefecture
# trace 27
# weight
5/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 28
# weight
3/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 29
# weight
7/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
# trace 30
# weight
2/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 31
# weight
16/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 32
# weight
4/12587
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 33
# weight
1/12587
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
# trace 34
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 35
# weight
3/12587
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
# trace 36
# weight
2/12587
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 37
# weight
2/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 38
# weight
5/12587
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
# trace 39
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 40
# weight
1/12587
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 41
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 42
# weight
2/12587
# number of events
3
Create Fine
Payment
Send Fine
# trace 43
# weight
3/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 44
# weight
1/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 45
# weight
3/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 46
# weight
1/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 47
# weight
1/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 48
# weight
1/12587
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 49
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 50
# weight
3/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Send for Credit Collection
# trace 51
# weight
2/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 52
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Send for Credit Collection
# trace 53
# weight
2/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 54
# weight
1/12587
# number of events
3
Create Fine
Appeal to Judge
Send Fine
# trace 55
# weight
1/12587
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 56
# weight
1/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Appeal to Judge
Payment
# trace 57
# weight
1/12587
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Payment
# trace 58
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 59
# weight
2/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 60
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 61
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 62
# weight
1/12587
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 63
# weight
1/12587
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 64
# weight
1/12587
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 65
# weight
1/12587
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment