finite stochastic language
# number of traces
47
# trace 0
# weight
259/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 1
# weight
8873/15336
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 2
# weight
455/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 3
# weight
11/15336
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 4
# weight
139/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 5
# weight
13/15336
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 6
# weight
1/15336
# number of events
16
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 7
# weight
131/3834
# number of events
2
Create Fine
Send Fine
# trace 8
# weight
1/15336
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 9
# weight
863/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 10
# weight
1/15336
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 11
# weight
419/15336
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 12
# weight
5/15336
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 13
# weight
227/7668
# number of events
3
Create Fine
Send Fine
Payment
# trace 14
# weight
13/3834
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 15
# weight
7/5112
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 16
# weight
5/1704
# number of events
3
Create Fine
Payment
Send Fine
# trace 17
# weight
1/3834
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 18
# weight
509/2556
# number of events
2
Create Fine
Payment
# trace 19
# weight
1/15336
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Payment
# trace 20
# weight
1/7668
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 21
# weight
1/7668
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Add penalty
Send for Credit Collection
# trace 22
# weight
2/1917
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 23
# weight
5/1704
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 24
# weight
1/5112
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 25
# weight
1/3834
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 26
# weight
5/5112
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 27
# weight
1/852
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 28
# weight
1/1278
# number of events
4
Create Fine
Send Fine
Payment
Payment
# trace 29
# weight
1/5112
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 30
# weight
1/15336
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Send for Credit Collection
# trace 31
# weight
1/15336
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 32
# weight
1/7668
# number of events
7
Create Fine
Send Fine
Payment
Insert Fine Notification
Payment
Add penalty
Payment
# trace 33
# weight
1/15336
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
Add penalty
Payment
# trace 34
# weight
1/15336
# number of events
4
Create Fine
Payment
Payment
Send Fine
# trace 35
# weight
1/5112
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 36
# weight
1/7668
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
# trace 37
# weight
1/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
# trace 38
# weight
1/15336
# number of events
9
Create Fine
Payment
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 39
# weight
1/15336
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 40
# weight
1/15336
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 41
# weight
1/15336
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
# trace 42
# weight
1/15336
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 43
# weight
1/15336
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 44
# weight
1/15336
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Payment
# trace 45
# weight
1/15336
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Payment
Add penalty
Send Appeal to Prefecture
# trace 46
# weight
1/15336
# number of events
3
Create Fine
Payment
Payment