finite stochastic language
# number of traces
72
# trace 0
# weight
2058/11555
# number of events
2
Create Fine
Payment
# trace 1
# weight
217/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 2
# weight
4684/11555
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 3
# weight
205/11555
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 4
# weight
1235/11555
# number of events
3
Create Fine
Send Fine
Payment
# trace 5
# weight
66/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 6
# weight
2076/11555
# number of events
2
Create Fine
Send Fine
# trace 7
# weight
319/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 8
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 9
# weight
2/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 10
# weight
157/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 11
# weight
170/11555
# number of events
3
Create Fine
Payment
Send Fine
# trace 12
# weight
13/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 13
# weight
6/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 14
# weight
93/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 15
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 16
# weight
8/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 17
# weight
16/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 18
# weight
4/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
Payment
# trace 19
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 20
# weight
10/11555
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 21
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
# trace 22
# weight
2/11555
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Payment
# trace 23
# weight
22/11555
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 24
# weight
49/11555
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 25
# weight
19/11555
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 26
# weight
14/11555
# number of events
4
Create Fine
Send Fine
Payment
Payment
# trace 27
# weight
4/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 28
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection
# trace 29
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Send Appeal to Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 30
# weight
4/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 31
# weight
2/11555
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 32
# weight
18/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 33
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 34
# weight
8/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 35
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 36
# weight
8/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 37
# weight
3/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 38
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 39
# weight
1/11555
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
# trace 40
# weight
4/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 41
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 42
# weight
1/11555
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 43
# weight
2/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 44
# weight
6/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 45
# weight
1/11555
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
# trace 46
# weight
2/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 47
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
# trace 48
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection
# trace 49
# weight
3/11555
# number of events
5
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Appeal to Judge
# trace 50
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 51
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 52
# weight
1/11555
# number of events
8
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Appeal to Judge
Send Appeal to Prefecture
Add penalty
Payment
# trace 53
# weight
2/11555
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 54
# weight
3/11555
# number of events
5
Create Fine
Send Fine
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 55
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 56
# weight
1/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
# trace 57
# weight
2/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 58
# weight
5/11555
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 59
# weight
1/11555
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 60
# weight
1/11555
# number of events
7
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Insert Fine Notification
Add penalty
Payment
# trace 61
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 62
# weight
1/11555
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 63
# weight
1/11555
# number of events
7
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 64
# weight
1/11555
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
Payment
# trace 65
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 66
# weight
2/11555
# number of events
7
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
# trace 67
# weight
1/11555
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Send Appeal to Prefecture
# trace 68
# weight
1/11555
# number of events
3
Create Fine
Send Fine
Appeal to Judge
# trace 69
# weight
1/11555
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
# trace 70
# weight
1/11555
# number of events
15
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
Payment
Payment
Payment
Payment
# trace 71
# weight
1/11555
# number of events
8
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Insert Fine Notification
Appeal to Judge
Add penalty
Payment