finite stochastic language
# number of traces
57
# trace 0
# weight
11/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 1
# weight
4433/10306
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 2
# weight
864/10306
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 3
# weight
2965/10306
# number of events
2
Create Fine
Payment
# trace 4
# weight
4/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 5
# weight
1/10306
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Send Fine
# trace 6
# weight
6/10306
# number of events
3
Create Fine
Payment
Send Fine
# trace 7
# weight
5/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 8
# weight
1136/10306
# number of events
2
Create Fine
Send Fine
# trace 9
# weight
312/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 10
# weight
30/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 11
# weight
111/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 12
# weight
4/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 13
# weight
263/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 14
# weight
1/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
# trace 15
# weight
1/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 16
# weight
1/10306
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
# trace 17
# weight
1/10306
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 18
# weight
1/10306
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 19
# weight
8/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
# trace 20
# weight
56/10306
# number of events
3
Create Fine
Send Fine
Payment
# trace 21
# weight
1/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 22
# weight
6/10306
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 23
# weight
2/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 24
# weight
12/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 25
# weight
1/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 26
# weight
1/10306
# number of events
8
Create Fine
Send Fine
Send Appeal to Prefecture
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 27
# weight
3/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 28
# weight
2/10306
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 29
# weight
2/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 30
# weight
2/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 31
# weight
16/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 32
# weight
1/10306
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
Payment
# trace 33
# weight
3/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
# trace 34
# weight
1/10306
# number of events
7
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
# trace 35
# weight
1/10306
# number of events
8
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Insert Fine Notification
Send Appeal to Prefecture
Add penalty
Payment
Payment
# trace 36
# weight
1/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Send for Credit Collection
# trace 37
# weight
5/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 38
# weight
1/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 39
# weight
2/10306
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 40
# weight
1/10306
# number of events
4
Create Fine
Insert Date Appeal to Prefecture
Send Fine
Send Appeal to Prefecture
# trace 41
# weight
4/10306
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 42
# weight
2/10306
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
Payment
Payment
Payment
Payment
# trace 43
# weight
2/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 44
# weight
2/10306
# number of events
6
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Send Appeal to Prefecture
# trace 45
# weight
1/10306
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 46
# weight
2/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
# trace 47
# weight
2/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 48
# weight
1/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
Payment
# trace 49
# weight
1/10306
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 50
# weight
2/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 51
# weight
3/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 52
# weight
2/10306
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Payment
Add penalty
Send Appeal to Prefecture
# trace 53
# weight
1/10306
# number of events
6
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Add penalty
Payment
# trace 54
# weight
1/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Send for Credit Collection
# trace 55
# weight
1/10306
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 56
# weight
1/10306
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
Payment
Payment