finite stochastic language
# number of traces
61
# trace 0
# weight
4018/8565
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 1
# weight
418/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 2
# weight
2301/8565
# number of events
2
Create Fine
Payment
# trace 3
# weight
237/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Payment
# trace 4
# weight
278/8565
# number of events
5
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 5
# weight
754/8565
# number of events
2
Create Fine
Send Fine
# trace 6
# weight
2/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Appeal to Judge
Payment
# trace 7
# weight
10/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 8
# weight
123/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Payment
Send for Credit Collection
# trace 9
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Payment
Send Appeal to Prefecture
# trace 10
# weight
10/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Send for Credit Collection
# trace 11
# weight
1/8565
# number of events
12
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
Payment
# trace 12
# weight
96/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
# trace 13
# weight
1/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 14
# weight
8/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 15
# weight
113/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Send for Credit Collection
# trace 16
# weight
1/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Payment
Payment
# trace 17
# weight
15/8565
# number of events
3
Create Fine
Payment
Send Fine
# trace 18
# weight
28/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 19
# weight
22/8565
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Payment
# trace 20
# weight
13/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 21
# weight
1/8565
# number of events
4
Create Fine
Payment
Send Fine
Payment
# trace 22
# weight
3/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 23
# weight
11/8565
# number of events
6
Create Fine
Payment
Send Fine
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 24
# weight
8/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 25
# weight
22/8565
# number of events
3
Create Fine
Send Fine
Payment
# trace 26
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Send for Credit Collection
# trace 27
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Payment
Add penalty
Send for Credit Collection
# trace 28
# weight
4/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
Payment
# trace 29
# weight
2/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Payment
Payment
Add penalty
Payment
# trace 30
# weight
3/8565
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Payment
# trace 31
# weight
1/8565
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 32
# weight
4/8565
# number of events
7
Create Fine
Payment
Send Fine
Insert Fine Notification
Payment
Add penalty
Payment
# trace 33
# weight
1/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 34
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
# trace 35
# weight
3/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 36
# weight
7/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
# trace 37
# weight
3/8565
# number of events
3
Create Fine
Payment
Payment
# trace 38
# weight
1/8565
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Payment
# trace 39
# weight
11/8565
# number of events
6
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
# trace 40
# weight
2/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
# trace 41
# weight
1/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
# trace 42
# weight
1/8565
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
# trace 43
# weight
1/8565
# number of events
4
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
# trace 44
# weight
1/8565
# number of events
6
Create Fine
Send Fine
Payment
Insert Fine Notification
Add penalty
Send for Credit Collection
# trace 45
# weight
1/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Appeal to Judge
Notify Result Appeal to Offender
Payment
# trace 46
# weight
1/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Add penalty
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Send for Credit Collection
# trace 47
# weight
1/8565
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Payment
Payment
Payment
Payment
# trace 48
# weight
3/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 49
# weight
1/8565
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Payment
Payment
# trace 50
# weight
1/8565
# number of events
8
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Appeal to Judge
# trace 51
# weight
1/8565
# number of events
11
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Send for Credit Collection
# trace 52
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Appeal to Judge
Add penalty
Payment
Payment
# trace 53
# weight
1/8565
# number of events
14
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Payment
Payment
Payment
Payment
Payment
Payment
# trace 54
# weight
3/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Add penalty
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
# trace 55
# weight
1/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Receive Result Appeal from Prefecture
Notify Result Appeal to Offender
Appeal to Judge
Send for Credit Collection
# trace 56
# weight
2/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Appeal to Judge
# trace 57
# weight
1/8565
# number of events
10
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
Payment
# trace 58
# weight
1/8565
# number of events
7
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Add penalty
Payment
# trace 59
# weight
1/8565
# number of events
9
Create Fine
Send Fine
Insert Fine Notification
Insert Date Appeal to Prefecture
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Payment
# trace 60
# weight
1/8565
# number of events
9
Create Fine
Send Fine
Insert Date Appeal to Prefecture
Insert Fine Notification
Send Appeal to Prefecture
Receive Result Appeal from Prefecture
Add penalty
Notify Result Appeal to Offender
Send for Credit Collection