finite stochastic language
# number of traces
108
# trace 0
# weight
12/819
# number of events
4
Accepted
Accepted
Accepted
Accepted
# trace 1
# weight
25/819
# number of events
3
Accepted
Accepted
Accepted
# trace 2
# weight
2/819
# number of events
7
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 3
# weight
3/819
# number of events
5
Accepted
Accepted
Accepted
Accepted
Accepted
# trace 4
# weight
4/819
# number of events
6
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 5
# weight
178/819
# number of events
2
Accepted
Completed
# trace 6
# weight
112/819
# number of events
2
Accepted
Accepted
# trace 7
# weight
1/819
# number of events
8
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
# trace 8
# weight
2/819
# number of events
4
Queued
Accepted
Accepted
Accepted
# trace 9
# weight
33/819
# number of events
4
Accepted
Accepted
Accepted
Completed
# trace 10
# weight
4/819
# number of events
4
Accepted
Accepted
Queued
Accepted
# trace 11
# weight
1/819
# number of events
8
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 12
# weight
8/819
# number of events
4
Accepted
Queued
Accepted
Accepted
# trace 13
# weight
50/819
# number of events
3
Accepted
Accepted
Completed
# trace 14
# weight
3/819
# number of events
4
Accepted
Accepted
Accepted
Queued
# trace 15
# weight
1/819
# number of events
7
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 16
# weight
38/819
# number of events
2
Accepted
Queued
# trace 17
# weight
17/819
# number of events
1
Queued
# trace 18
# weight
1/819
# number of events
8
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 19
# weight
5/819
# number of events
6
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 20
# weight
1/819
# number of events
7
Accepted
Accepted
Queued
Queued
Queued
Accepted
Accepted
# trace 21
# weight
6/819
# number of events
5
Accepted
Accepted
Accepted
Accepted
Completed
# trace 22
# weight
1/819
# number of events
7
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
# trace 23
# weight
1/819
# number of events
7
Queued
Queued
Queued
Queued
Accepted
Accepted
Completed
# trace 24
# weight
3/819
# number of events
6
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 25
# weight
6/819
# number of events
3
Accepted
Accepted
Queued
# trace 26
# weight
5/819
# number of events
2
Queued
Accepted
# trace 27
# weight
1/819
# number of events
7
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 28
# weight
11/819
# number of events
3
Queued
Accepted
Completed
# trace 29
# weight
1/819
# number of events
5
Queued
Queued
Accepted
Accepted
Completed
# trace 30
# weight
1/819
# number of events
8
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Queued
# trace 31
# weight
27/819
# number of events
3
Accepted
Queued
Accepted
# trace 32
# weight
1/819
# number of events
9
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 33
# weight
1/819
# number of events
7
Accepted
Queued
Queued
Queued
Queued
Accepted
Completed
# trace 34
# weight
4/819
# number of events
3
Accepted
Queued
Queued
# trace 35
# weight
5/819
# number of events
5
Accepted
Queued
Accepted
Queued
Accepted
# trace 36
# weight
1/819
# number of events
9
Accepted
Queued
Accepted
Queued
Queued
Queued
Accepted
Completed
Accepted
# trace 37
# weight
3/819
# number of events
6
Accepted
Queued
Queued
Accepted
Accepted
Completed
# trace 38
# weight
3/819
# number of events
5
Queued
Accepted
Completed
Accepted
Completed
# trace 39
# weight
9/819
# number of events
4
Accepted
Queued
Accepted
Completed
# trace 40
# weight
1/819
# number of events
5
Accepted
Queued
Queued
Accepted
Completed
# trace 41
# weight
1/819
# number of events
10
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Accepted
Queued
# trace 42
# weight
2/819
# number of events
4
Accepted
Queued
Accepted
Queued
# trace 43
# weight
138/819
# number of events
1
Accepted
# trace 44
# weight
3/819
# number of events
4
Accepted
Completed
Accepted
Completed
# trace 45
# weight
1/819
# number of events
5
Accepted
Completed
Accepted
Accepted
Queued
# trace 46
# weight
1/819
# number of events
6
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 47
# weight
8/819
# number of events
5
Accepted
Queued
Accepted
Accepted
Completed
# trace 48
# weight
1/819
# number of events
7
Queued
Accepted
Queued
Queued
Queued
Queued
Accepted
# trace 49
# weight
1/819
# number of events
7
Accepted
Queued
Accepted
Completed
Accepted
Accepted
Completed
# trace 50
# weight
2/819
# number of events
4
Accepted
Queued
Queued
Accepted
# trace 51
# weight
1/819
# number of events
9
Accepted
Completed
Accepted
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 52
# weight
3/819
# number of events
7
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 53
# weight
1/819
# number of events
7
Accepted
Accepted
Accepted
Queued
Queued
Accepted
Completed
# trace 54
# weight
1/819
# number of events
19
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Accepted
Completed
Accepted
Accepted
Accepted
Completed
Accepted
Completed
# trace 55
# weight
1/819
# number of events
8
Accepted
Completed
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 56
# weight
1/819
# number of events
4
Accepted
Accepted
Queued
Queued
# trace 57
# weight
2/819
# number of events
4
Accepted
Completed
Accepted
Queued
# trace 58
# weight
2/819
# number of events
3
Queued
Accepted
Accepted
# trace 59
# weight
2/819
# number of events
5
Queued
Accepted
Accepted
Accepted
Completed
# trace 60
# weight
1/819
# number of events
7
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
# trace 61
# weight
1/819
# number of events
5
Queued
Queued
Queued
Accepted
Completed
# trace 62
# weight
1/819
# number of events
2
Queued
Queued
# trace 63
# weight
2/819
# number of events
7
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 64
# weight
1/819
# number of events
9
Accepted
Completed
Accepted
Completed
Accepted
Accepted
Completed
Accepted
Completed
# trace 65
# weight
2/819
# number of events
5
Accepted
Accepted
Completed
Accepted
Completed
# trace 66
# weight
1/819
# number of events
9
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 67
# weight
1/819
# number of events
7
Accepted
Queued
Queued
Queued
Accepted
Accepted
Completed
# trace 68
# weight
1/819
# number of events
9
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 69
# weight
1/819
# number of events
9
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 70
# weight
1/819
# number of events
15
Accepted
Queued
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 71
# weight
2/819
# number of events
4
Accepted
Queued
Queued
Queued
# trace 72
# weight
1/819
# number of events
11
Accepted
Accepted
Queued
Queued
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 73
# weight
1/819
# number of events
8
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
# trace 74
# weight
1/819
# number of events
9
Accepted
Accepted
Completed
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 75
# weight
1/819
# number of events
8
Accepted
Queued
Queued
Queued
Accepted
Queued
Accepted
Queued
# trace 76
# weight
1/819
# number of events
5
Accepted
Accepted
Queued
Accepted
Queued
# trace 77
# weight
1/819
# number of events
7
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 78
# weight
2/819
# number of events
9
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 79
# weight
1/819
# number of events
22
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
# trace 80
# weight
1/819
# number of events
8
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
# trace 81
# weight
1/819
# number of events
3
Accepted
Completed
Accepted
# trace 82
# weight
2/819
# number of events
6
Accepted
Queued
Accepted
Queued
Accepted
Accepted
# trace 83
# weight
1/819
# number of events
11
Accepted
Queued
Queued
Accepted
Accepted
Queued
Queued
Accepted
Completed
Accepted
Completed
# trace 84
# weight
1/819
# number of events
10
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
# trace 85
# weight
1/819
# number of events
6
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
# trace 86
# weight
1/819
# number of events
1
Completed
# trace 87
# weight
1/819
# number of events
8
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
# trace 88
# weight
1/819
# number of events
9
Queued
Accepted
Completed
Accepted
Queued
Accepted
Queued
Accepted
Accepted
# trace 89
# weight
1/819
# number of events
6
Accepted
Queued
Queued
Queued
Accepted
Queued
# trace 90
# weight
3/819
# number of events
5
Accepted
Queued
Accepted
Accepted
Accepted
# trace 91
# weight
1/819
# number of events
3
Queued
Accepted
Queued
# trace 92
# weight
1/819
# number of events
9
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
# trace 93
# weight
1/819
# number of events
9
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
# trace 94
# weight
1/819
# number of events
5
Accepted
Queued
Queued
Accepted
Queued
# trace 95
# weight
1/819
# number of events
7
Accepted
Queued
Accepted
Queued
Queued
Accepted
Accepted
# trace 96
# weight
1/819
# number of events
6
Queued
Accepted
Accepted
Queued
Accepted
Accepted
# trace 97
# weight
1/819
# number of events
8
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
# trace 98
# weight
1/819
# number of events
9
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
# trace 99
# weight
1/819
# number of events
4
Queued
Accepted
Accepted
Queued
# trace 100
# weight
1/819
# number of events
6
Accepted
Queued
Accepted
Accepted
Queued
Accepted
# trace 101
# weight
1/819
# number of events
7
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
# trace 102
# weight
1/819
# number of events
11
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
# trace 103
# weight
1/819
# number of events
5
Accepted
Queued
Accepted
Accepted
Queued
# trace 104
# weight
1/819
# number of events
6
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
# trace 105
# weight
1/819
# number of events
5
Accepted
Queued
Accepted
Queued
Queued
# trace 106
# weight
1/819
# number of events
3
Queued
Queued
Accepted
# trace 107
# weight
1/819
# number of events
7
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted