finite stochastic language
# number of traces
183
# trace 0
# weight
1/1487
# number of events
5
Queued
Accepted
Accepted
Accepted
Completed
# trace 1
# weight
16/1487
# number of events
6
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 2
# weight
55/1487
# number of events
5
Accepted
Accepted
Accepted
Accepted
Completed
# trace 3
# weight
11/1487
# number of events
7
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 4
# weight
15/1487
# number of events
7
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 5
# weight
3/1487
# number of events
8
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 6
# weight
230/1487
# number of events
3
Accepted
Accepted
Completed
# trace 7
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 8
# weight
3/1487
# number of events
3
Accepted
Unmatched
Completed
# trace 9
# weight
1/1487
# number of events
10
Queued
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 10
# weight
493/1487
# number of events
2
Accepted
Completed
# trace 11
# weight
5/1487
# number of events
9
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 12
# weight
1/1487
# number of events
10
Accepted
Unmatched
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 13
# weight
4/1487
# number of events
9
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 14
# weight
9/1487
# number of events
6
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 15
# weight
1/1487
# number of events
6
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 16
# weight
1/1487
# number of events
13
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 17
# weight
1/1487
# number of events
5
Accepted
Queued
Accepted
Unmatched
Completed
# trace 18
# weight
1/1487
# number of events
4
Unmatched
Accepted
Accepted
Completed
# trace 19
# weight
5/1487
# number of events
5
Accepted
Queued
Queued
Accepted
Completed
# trace 20
# weight
95/1487
# number of events
4
Accepted
Accepted
Accepted
Completed
# trace 21
# weight
142/1487
# number of events
6
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 22
# weight
6/1487
# number of events
5
Queued
Accepted
Queued
Accepted
Completed
# trace 23
# weight
1/1487
# number of events
11
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 24
# weight
1/1487
# number of events
8
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 25
# weight
2/1487
# number of events
10
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 26
# weight
1/1487
# number of events
6
Accepted
Unmatched
Accepted
Accepted
Accepted
Completed
# trace 27
# weight
1/1487
# number of events
10
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 28
# weight
14/1487
# number of events
7
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 29
# weight
1/1487
# number of events
6
Accepted
Accepted
Queued
Accepted
Unmatched
Completed
# trace 30
# weight
1/1487
# number of events
4
Accepted
Unmatched
Accepted
Completed
# trace 31
# weight
1/1487
# number of events
10
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 32
# weight
9/1487
# number of events
8
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 33
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 34
# weight
3/1487
# number of events
13
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 35
# weight
1/1487
# number of events
8
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 36
# weight
1/1487
# number of events
8
Accepted
Unmatched
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 37
# weight
1/1487
# number of events
11
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 38
# weight
1/1487
# number of events
8
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 39
# weight
1/1487
# number of events
8
Queued
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 40
# weight
1/1487
# number of events
13
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 41
# weight
1/1487
# number of events
17
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Completed
Accepted
Queued
Accepted
Completed
# trace 42
# weight
1/1487
# number of events
10
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 43
# weight
34/1487
# number of events
5
Accepted
Queued
Accepted
Accepted
Completed
# trace 44
# weight
5/1487
# number of events
8
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 45
# weight
3/1487
# number of events
12
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 46
# weight
5/1487
# number of events
8
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 47
# weight
2/1487
# number of events
7
Accepted
Accepted
Accepted
Completed
Accepted
Accepted
Completed
# trace 48
# weight
1/1487
# number of events
17
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 49
# weight
1/1487
# number of events
14
Accepted
Queued
Accepted
Accepted
Accepted
Completed
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 50
# weight
2/1487
# number of events
12
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 51
# weight
2/1487
# number of events
11
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 52
# weight
1/1487
# number of events
14
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 53
# weight
1/1487
# number of events
13
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 54
# weight
23/1487
# number of events
3
Queued
Accepted
Completed
# trace 55
# weight
4/1487
# number of events
5
Accepted
Completed
Accepted
Accepted
Completed
# trace 56
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 57
# weight
4/1487
# number of events
9
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 58
# weight
2/1487
# number of events
8
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 59
# weight
67/1487
# number of events
4
Accepted
Queued
Accepted
Completed
# trace 60
# weight
1/1487
# number of events
13
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 61
# weight
1/1487
# number of events
18
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 62
# weight
1/1487
# number of events
22
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 63
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 64
# weight
1/1487
# number of events
15
Accepted
Queued
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 65
# weight
1/1487
# number of events
6
Queued
Queued
Accepted
Queued
Accepted
Completed
# trace 66
# weight
2/1487
# number of events
11
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 67
# weight
4/1487
# number of events
7
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 68
# weight
1/1487
# number of events
9
Accepted
Accepted
Accepted
Completed
Accepted
Accepted
Accepted
Accepted
Completed
# trace 69
# weight
1/1487
# number of events
16
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 70
# weight
1/1487
# number of events
29
Accepted
Accepted
Accepted
Completed
Accepted
Queued
Accepted
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 71
# weight
2/1487
# number of events
11
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 72
# weight
2/1487
# number of events
13
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 73
# weight
1/1487
# number of events
7
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 74
# weight
2/1487
# number of events
8
Accepted
Queued
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 75
# weight
12/1487
# number of events
6
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 76
# weight
1/1487
# number of events
14
Accepted
Queued
Queued
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 77
# weight
2/1487
# number of events
9
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 78
# weight
1/1487
# number of events
19
Accepted
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 79
# weight
1/1487
# number of events
10
Accepted
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 80
# weight
1/1487
# number of events
14
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 81
# weight
1/1487
# number of events
13
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 82
# weight
9/1487
# number of events
7
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 83
# weight
1/1487
# number of events
11
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 84
# weight
1/1487
# number of events
10
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 85
# weight
2/1487
# number of events
8
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 86
# weight
1/1487
# number of events
8
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 87
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 88
# weight
2/1487
# number of events
4
Queued
Queued
Accepted
Completed
# trace 89
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 90
# weight
2/1487
# number of events
6
Accepted
Queued
Queued
Queued
Accepted
Completed
# trace 91
# weight
2/1487
# number of events
10
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 92
# weight
1/1487
# number of events
7
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 93
# weight
1/1487
# number of events
14
Accepted
Queued
Queued
Queued
Queued
Accepted
Accepted
Queued
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 94
# weight
1/1487
# number of events
9
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 95
# weight
1/1487
# number of events
12
Accepted
Queued
Queued
Queued
Queued
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 96
# weight
1/1487
# number of events
7
Accepted
Queued
Accepted
Queued
Queued
Accepted
Completed
# trace 97
# weight
7/1487
# number of events
5
Accepted
Accepted
Queued
Accepted
Completed
# trace 98
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 99
# weight
2/1487
# number of events
6
Accepted
Queued
Queued
Accepted
Accepted
Completed
# trace 100
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Accepted
Accepted
Completed
# trace 101
# weight
1/1487
# number of events
13
Accepted
Accepted
Completed
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Queued
Queued
Accepted
Completed
# trace 102
# weight
3/1487
# number of events
6
Accepted
Completed
Accepted
Queued
Accepted
Completed
# trace 103
# weight
1/1487
# number of events
6
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 104
# weight
3/1487
# number of events
5
Queued
Accepted
Completed
Accepted
Completed
# trace 105
# weight
1/1487
# number of events
7
Accepted
Accepted
Accepted
Queued
Queued
Accepted
Completed
# trace 106
# weight
2/1487
# number of events
7
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 107
# weight
3/1487
# number of events
4
Queued
Accepted
Accepted
Completed
# trace 108
# weight
1/1487
# number of events
15
Accepted
Queued
Accepted
Queued
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 109
# weight
1/1487
# number of events
19
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 110
# weight
1/1487
# number of events
8
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 111
# weight
1/1487
# number of events
7
Accepted
Queued
Queued
Queued
Accepted
Accepted
Completed
# trace 112
# weight
1/1487
# number of events
6
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 113
# weight
1/1487
# number of events
8
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Completed
# trace 114
# weight
9/1487
# number of events
4
Accepted
Completed
Accepted
Completed
# trace 115
# weight
1/1487
# number of events
7
Accepted
Completed
Accepted
Accepted
Queued
Accepted
Completed
# trace 116
# weight
2/1487
# number of events
6
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 117
# weight
1/1487
# number of events
35
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 118
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
Accepted
Completed
# trace 119
# weight
1/1487
# number of events
18
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 120
# weight
2/1487
# number of events
7
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 121
# weight
1/1487
# number of events
11
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 122
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Completed
Accepted
Accepted
Accepted
Accepted
Completed
# trace 123
# weight
3/1487
# number of events
7
Accepted
Queued
Queued
Accepted
Queued
Accepted
Completed
# trace 124
# weight
1/1487
# number of events
9
Accepted
Completed
Accepted
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 125
# weight
1/1487
# number of events
17
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 126
# weight
1/1487
# number of events
13
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Accepted
Accepted
Completed
Accepted
Accepted
Completed
# trace 127
# weight
1/1487
# number of events
11
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
Accepted
Completed
# trace 128
# weight
2/1487
# number of events
6
Accepted
Accepted
Accepted
Completed
Accepted
Completed
# trace 129
# weight
1/1487
# number of events
7
Accepted
Completed
Accepted
Accepted
Accepted
Accepted
Completed
# trace 130
# weight
1/1487
# number of events
9
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 131
# weight
1/1487
# number of events
11
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 132
# weight
1/1487
# number of events
19
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Accepted
Completed
Accepted
Accepted
Accepted
Completed
Accepted
Completed
# trace 133
# weight
1/1487
# number of events
7
Accepted
Accepted
Accepted
Accepted
Completed
Accepted
Completed
# trace 134
# weight
1/1487
# number of events
9
Accepted
Completed
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 135
# weight
1/1487
# number of events
8
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Completed
# trace 136
# weight
1/1487
# number of events
6
Accepted
Queued
Accepted
Completed
Accepted
Completed
# trace 137
# weight
1/1487
# number of events
10
Accepted
Accepted
Queued
Accepted
Completed
Accepted
Queued
Accepted
Accepted
Completed
# trace 138
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 139
# weight
1/1487
# number of events
13
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Completed
# trace 140
# weight
1/1487
# number of events
11
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 141
# weight
1/1487
# number of events
8
Accepted
Completed
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 142
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 143
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Accepted
Accepted
Completed
Accepted
Queued
Accepted
Completed
Accepted
Completed
# trace 144
# weight
1/1487
# number of events
9
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 145
# weight
1/1487
# number of events
12
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 146
# weight
1/1487
# number of events
7
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 147
# weight
2/1487
# number of events
7
Accepted
Accepted
Completed
Accepted
Queued
Accepted
Completed
# trace 148
# weight
1/1487
# number of events
14
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 149
# weight
2/1487
# number of events
11
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 150
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 151
# weight
1/1487
# number of events
28
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Queued
Accepted
Completed
# trace 152
# weight
1/1487
# number of events
10
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 153
# weight
1/1487
# number of events
9
Accepted
Accepted
Queued
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 154
# weight
1/1487
# number of events
7
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Completed
# trace 155
# weight
1/1487
# number of events
9
Queued
Accepted
Accepted
Queued
Queued
Accepted
Completed
Accepted
Completed
# trace 156
# weight
1/1487
# number of events
13
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 157
# weight
1/1487
# number of events
10
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 158
# weight
1/1487
# number of events
8
Accepted
Completed
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 159
# weight
1/1487
# number of events
10
Accepted
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 160
# weight
2/1487
# number of events
5
Accepted
Accepted
Completed
Accepted
Completed
# trace 161
# weight
1/1487
# number of events
9
Accepted
Completed
Accepted
Completed
Accepted
Accepted
Completed
Accepted
Completed
# trace 162
# weight
1/1487
# number of events
16
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 163
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Accepted
Completed
# trace 164
# weight
1/1487
# number of events
7
Accepted
Queued
Accepted
Accepted
Completed
Accepted
Completed
# trace 165
# weight
1/1487
# number of events
9
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 166
# weight
1/1487
# number of events
14
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 167
# weight
1/1487
# number of events
8
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Completed
# trace 168
# weight
1/1487
# number of events
19
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 169
# weight
1/1487
# number of events
6
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 170
# weight
1/1487
# number of events
12
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 171
# weight
1/1487
# number of events
18
Accepted
Queued
Queued
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 172
# weight
1/1487
# number of events
13
Accepted
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Accepted
Completed
# trace 173
# weight
1/1487
# number of events
11
Accepted
Queued
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Completed
# trace 174
# weight
1/1487
# number of events
9
Accepted
Accepted
Completed
Accepted
Completed
Accepted
Completed
Accepted
Completed
# trace 175
# weight
1/1487
# number of events
12
Accepted
Queued
Accepted
Queued
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 176
# weight
1/1487
# number of events
9
Accepted
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 177
# weight
1/1487
# number of events
10
Accepted
Accepted
Queued
Queued
Accepted
Queued
Accepted
Accepted
Accepted
Completed
# trace 178
# weight
2/1487
# number of events
13
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Queued
Accepted
Accepted
Completed
# trace 179
# weight
1/1487
# number of events
11
Accepted
Queued
Queued
Accepted
Accepted
Queued
Queued
Accepted
Completed
Accepted
Completed
# trace 180
# weight
1/1487
# number of events
8
Accepted
Accepted
Accepted
Accepted
Accepted
Queued
Accepted
Completed
# trace 181
# weight
1/1487
# number of events
1
Completed
# trace 182
# weight
1/1487
# number of events
8
Accepted
Completed
Accepted
Completed
Accepted
Accepted
Accepted
Completed